export const MENU_ITEMS = [
  // ---------------- TACOS ----------------
  {
    id: 1,
    category: "tacos",
    type: "Taco",
    title: "Pastor",
    price: 14,
    description: "Carne de cerdo adobada, cilantro y cebolla.",
    image: "Taco_pastorMMM_a9vjpo",
  },
  {
    id: 2,
    category: "tacos",
    type: "Taco",
    title: "Chorizo",
    price: 16,
    description: "Chorizo dorado, cilantro y cebolla.",
    image: "Taco_chorizo_nw4cho",
  },
  {
    id: 3,
    category: "tacos",
    type: "Taco",
    title: "Arrachera",
    price: 16,
    description: "Arrachera marinada, cilantro y cebolla.",
    image: "Taco_Arrachera_hsv5sb",
  },
  {
    id: 4,
    category: "tacos",
    type: "Taco",
    title: "Bisteck",
    price: 16,
    description: "Bisteck picado y jugoso, cilantro y cebolla.",
    image: "Taco_Bisteck_mdontk",
  },
  {
    id: 5,
    category: "tacos",
    type: "Taco",
    title: "Campechano",
    price: 20,
    description: "Mezcla de bisteck y chorizo.",
    image: "",
  },

  // ---------------- QUESATACO ----------------
  {
    id: 6,
    category: "quesataco",
    type: "Quesataco",
    title: "Pastor",
    price: 20,
    description: "Quesataco de pastor con queso derretido.",
    image: "Quesataco_pastor_l4axbh",
  },
  {
    id: 7,
    category: "quesataco",
    type: "Quesataco",
    title: "Chorizo",
    price: 25,
    description: "Quesataco relleno de chorizo.",
    image: "",
  },
  {
    id: 8,
    category: "quesataco",
    type: "Quesataco",
    title: "Arrachera",
    price: 25,
    description: "Arrachera jugosa con queso fundido.",
    image: "",
  },
  {
    id: 9,
    category: "quesataco",
    type: "Quesataco",
    title: "Bisteck",
    price: 25,
    description: "Queso derretido con bisteck tierno.",
    image: "",
  },
  {
    id: 10,
    category: "quesataco",
    type: "Quesataco",
    title: "Campechano",
    price: 30,
    description: "Bisteck + chorizo con queso.",
    image: "",
  },

  // ---------------- GRINGAS ----------------
  {
    id: 11,
    category: "gringas",
    type: "Gringa",
    title: "Pastor",
    price: 42,
    description: "Tortilla de harina con pastor y queso.",
    image: "",
  },
  {
    id: 12,
    category: "gringas",
    type: "Gringa",
    title: "Chorizo",
    price: 47,
    description: "Gringa de chorizo dorado.",
    image: "",
  },
  {
    id: 13,
    category: "gringas",
    type: "Gringa",
    title: "Arrachera",
    price: 47,
    description: "Arrachera y queso en tortilla de harina.",
    image: "",
  },
  {
    id: 14,
    category: "gringas",
    type: "Gringa",
    title: "Bisteck",
    price: 47,
    description: "Bisteck jugoso con queso fundido.",
    image: "",
  },  
  {
    id: 15,
    category: "gringas",
    type: "Gringa",
    title: "Campechano",
    price: 55,
    description: "Bisteck y chorizo con queso.",
    image: "",
  },

  // ---------------- ALAMBRES ----------------
  {
    id: 16,
    category: "alambres",
    type: "Alambre",
    title: "Pastor",
    price: 115,
    description: "Pimientos, cebolla, tocino y queso.",
    image: "",
  },
  {
    id: 17,
    category: "alambres",
    type: "Alambre",
    title: "Chorizo",
    price: 125,
    description: "Alambre de chorizo con queso.",
    image: "",
  },
  {
    id: 18,
    category: "alambres",
    type: "Alambre",
    title: "Arrachera",
    price: 125,
    description: "Arrachera asada con verduras y queso.",
    image: "",
  },
  {
    id: 19,
    category: "alambres",
    type: "Alambre",
    title: "Bisteck",
    price: 125,
    description: "Bisteck con pimientos, tocino y queso.",
    image: "Alambre_khbzlt.png",
  },
  {
    id: 20,
    category: "alambres",
    type: "Alambre",
    title: "Campechano",
    price: 135,
    description: "Chorizo + bisteck + queso.",
    image: "",
  },

  // ---------------- VOLCANES ----------------
  {
    id: 21,
    category: "volcanes",
    type: "Volcán",
    title: "Pastor",
    price: 20,
    description: "Tostada crujiente con queso y pastor.",
    image: "",
  },
  {
    id: 22,
    category: "volcanes",
    type: "Volcán",
    title: "Chorizo",
    price: 22,
    description: "Volcán de chorizo con queso derretido.",
    image: "",
  },
  {
    id: 23,
    category: "volcanes",
    type: "Volcán",
    title: "Arrachera",
    price: 25,
    description: "Arrachera jugosa sobre tostada con queso.",
    image: "",
  },
  {
    id: 24,
    category: "volcanes",
    type: "Volcán",
    title: "Bisteck",
    price: 25,
    description: "Bisteck picado con queso fundido.",
    image: "",
  },
  {
    id: 25,
    category: "volcanes",
    type: "Volcán",
    title: "Campechano",
    price: 28,
    description: "Mezcla de bisteck y chorizo con queso.",
    image: "Volcan_campechano_e3dmtz",
  },

  // ---------------- especial DE LA CASA ----------------
  {
    id: 26,
    category: "especial",
    type: "Burrito",
    title: "Burrito de Pastor",
    price: 85,
    description: "Delicioso burrito relleno de pastor.",
    image: "Burrito_pastor_exo5jh.png",
  },
  {
    id: 27,
    category: "especial",
    type: "Burrito",
    title: "Burrito Arrachera/Bisteck",
    price: 100,
    description: "Burrito con arrachera o bisteck a elegir.",
    image: "",
  },
  {
    id: 28,
    category: "especial",
    type: "Burrito",
    title: "Burrito de Chorizo",
    price: 100,
    description: "Burrito relleno de chorizo dorado.",
    image: "",
  },
  {
    id: 29,
    category: "especial",
    type: "Burrito",
    title: "Burrito Campechano",
    price: 115,
    description: "Mezcla de bisteck y chorizo en burrito.",
    image: "",
  },

  // ---------------- HAMBURGUESAS ----------------
  {
    id: 30,
    category: "hamburguesas",
    type: "Hamburguesa",
    title: "Pastor",
    price: 70,
    description: "Hamburguesa con carne de pastor.",
    image: "",
  },
  {
    id: 31,
    category: "hamburguesas",
    type: "Hamburguesa",
    title: "Chorizo",
    price: 80,
    description: "Hamburguesa de chorizo.",
    image: "",
  },
  {
    id: 32,
    category: "hamburguesas",
    type: "Hamburguesa",
    title: "Arrachera",
    price: 80,
    description: "Hamburguesa de arrachera.",
    image: "",
  },
  {
    id: 33,
    category: "hamburguesas",
    type: "Hamburguesa",
    title: "Bisteck",
    price: 80,
    description: "Hamburguesa de bisteck.",
    image: "",
  },
  {
    id: 34,
    category: "hamburguesas",
    type: "Hamburguesa",
    title: "Campechano",
    price: 90,
    description: "Hamburguesa campechana con mezcla de carnes.",
    image: "",
  },
  {
    id: 35,
    category: "hamburguesas",
    type: "Hamburguesa",
    title: "Hames",
    price: 150,
    description: "Hamburguesa especial Hames.",
    image: "",
  },

  // ---------------- HAMBURGUESAS DOBLES ----------------
  {
    id: 36,
    category: "hamburguesas",
    type: "Hamburguesa Doble",
    title: "Pastor Doble",
    price: 100,
    description: "Hamburguesa doble de pastor.",
    image: "",
  },
  {
    id: 37,
    category: "hamburguesas",
    type: "Hamburguesa Doble",
    title: "Chorizo Doble",
    price: 115,
    description: "Hamburguesa doble de chorizo.",
    image: "",
  },
  {
    id: 38,
    category: "hamburguesas",
    type: "Hamburguesa Doble",
    title: "Arrachera Doble",
    price: 115,
    description: "Hamburguesa doble de arrachera.",
    image: "",
  },
  {
    id: 39,
    category: "hamburguesas",
    type: "Hamburguesa Doble",
    title: "Bisteck Doble",
    price: 115,
    description: "Hamburguesa doble de bisteck.",
    image: "",
  },
  {
    id: 40,
    category: "hamburguesas",
    type: "Hamburguesa Doble",
    title: "Campechano Doble",
    price: 125,
    description: "Hamburguesa doble campechana.",
    image: "",
  },
    // ---------------- GROSERIAS (COCHADA) ----------------
  {
    id: 41,
    category: "groserias",
    type: "Groseria",
    title: "Pastor",
    price: 90,
    description: "Groseria de pastor con queso y guarniciones.",
    image: "",
  },
  {
    id: 42,
    category: "groserias",
    type: "Groseria",
    title: "Chorizo",
    price: 95,
    description: "Groseria de chorizo con queso y guarniciones.",
    image: "",
  },
  {
    id: 43,
    category: "groserias",
    type: "Groseria",
    title: "Arrachera",
    price: 95,
    description: "Groseria de arrachera con queso y guarniciones.",
    image: "",
  },
  {
    id: 44,
    category: "groserias",
    type: "Groseria",
    title: "Bisteck",
    price: 95,
    description: "Groseria de bisteck con queso y guarniciones.",
    image: "",
  },
  {
    id: 45,
    category: "groserias",
    type: "Groseria",
    title: "Campechano",
    price: 110,
    description: "Groseria campechana con queso y guarniciones.",
    image: "",
  },

  // ---------------- TOTOPOS ----------------
  {
    id: 46,
    category: "totopos",
    type: "Totopo",
    title: "Pastor",
    price: 90,
    description: "Totopos con pastor, queso y guarniciones.",
    image: "Totopos_xuilfr",
  },
  {
    id: 47,
    category: "totopos",
    type: "Totopo",
    title: "Chorizo",
    price: 100,
    description: "Totopos con chorizo, queso y guarniciones.",
    image: "",
  },
  {
    id: 48,
    category: "totopos",
    type: "Totopo",
    title: "Arrachera",
    price: 100,
    description: "Totopos con arrachera, queso y guarniciones.",
    image: "",
  },
  {
    id: 49,
    category: "totopos",
    type: "Totopo",
    title: "Bisteck",
    price: 100,
    description: "Totopos con bisteck, queso y guarniciones.",
    image: "",
  },
  {
    id: 50,
    category: "totopos",
    type: "Totopo",
    title: "Campechano",
    price: 110,
    description: "Totopos campechanos con queso y guarniciones.",
    image: "",
  },

  // ---------------- KILO ----------------
  {
    id: 51,
    category: "kilo",
    type: "Kilo",
    title: "Pastor",
    price: 400,
    description: "1 kilo de pastor para compartir.",
    image: "",
  },
  {
    id: 52,
    category: "kilo",
    type: "Kilo",
    title: "Chorizo",
    price: 450,
    description: "1 kilo de chorizo para compartir.",
    image: "",
  },
  {
    id: 53,
    category: "kilo",
    type: "Kilo",
    title: "Arrachera",
    price: 450,
    description: "1 kilo de arrachera para compartir.",
    image: "",
  },
  {
    id: 54,
    category: "kilo",
    type: "Kilo",
    title: "Campechano",
    price: 450,
    description: "1 kilo de mezcla campechana para compartir.",
    image: "",
  },

  // ---------------- BEBIDAS ----------------
  {
    id: 55,
    category: "bebidas",
    type: "Bebida",
    title: "Refresco/Jugo",
    price: 22,
    description: "Refresco o jugo de sabores.",
    image: "",
  },
  {
    id: 56,
    category: "bebidas",
    type: "Bebida",
    title: "Agua de sabor",
    price: 20,
    description: "Agua fresca de sabores.",
    image: "",
  },
  {
    id: 57,
    category: "bebidas",
    type: "Bebida",
    title: "Agua embotellada",
    price: 15,
    description: "Agua purificada embotellada.",
    image: "",
  },
    // ---------------- QUESADILLAS ----------------
  {
    id: 58,
    category: "quesadillas",
    type: "Quesadilla",
    title: "Pastor",
    price: 32,
    description: "Quesadilla de pastor con queso derretido.",
    image: "",
  },
  {
    id: 59,
    category: "quesadillas",
    type: "Quesadilla",
    title: "Chorizo",
    price: 35,
    description: "Quesadilla de chorizo con queso.",
    image: "",
  },
  {
    id: 60,
    category: "quesadillas",
    type: "Quesadilla",
    title: "Arrachera",
    price: 35,
    description: "Quesadilla de arrachera con queso fundido.",
    image: "",
  },
  {
    id: 61,
    category: "quesadillas",
    type: "Quesadilla",
    title: "Bisteck",
    price: 35,
    description: "Quesadilla de bisteck con queso.",
    image: "",
  },
  {
    id: 62,
    category: "quesadillas",
    type: "Quesadilla",
    title: "Campechano",
    price: 40,
    description: "Quesadilla campechana con mezcla de carnes y queso.",
    image: "",
  },
];